name: Deploy blog

on:
  pull_request:
    paths: ['src/**', 'tests/**', 'theme/**']
  push:
    paths: ['src/**', 'spa/**', 'posts/**', 'tests/**', 'theme/**', 'VERSION']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Cache nuget package
      uses: actions/cache@v1
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore nuget packages
      run: dotnet restore
    - name: Test
      run: dotnet test --no-restore
    - name: Build release
      run: dotnet build -c Release --no-restore
    - name: Publish release
      run: dotnet publish -c Release -o out --no-build
    - name: Generate blog files
      run: dotnet ./out/blog.dll --cwd ./

    - name: Deploy to Staging
      id: deploy-vercel-staging
      uses: amondnet/vercel-action@v20
      #preview on staging
      if: |
        github.event_name == 'push' &&
        github.ref == 'refs/heads/main' &&
        startsWith(github.event.head_commit.message, 'preview:')
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./dist
        scope: ${{ secrets.VERCEL_ORG_ID }}

    - name: Deploy to Production
      uses: amondnet/vercel-action@v20
      id: deploy-vercel-production
      #deploy to production
      if: |
        github.event_name == 'push' &&
        github.ref == 'refs/heads/main' &&
        startsWith(github.event.head_commit.message, 'release:')
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'
        working-directory: ./dist
        scope: ${{ secrets.VERCEL_ORG_ID }}
